services:
  database:
    image: "postgres:16.0-alpine"
    env_file:
      - ".env.development"
    expose:
      - "3003"
    ports:
      - "3003:5432"
    volumes:
      - ./:/docker-entrypoint-initdb.d
