services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
  database:
    image: "postgres:16.0-alpine"
    env_file:
      - ".env.development"
    ports:
      - "5432:5432"
    volumes:
      - ./:/docker-entrypoint-initdb.d
